// svelte/src/Button.svelte
<script></script>
<style>
  button {
    font-size: 14px;
    display: inline-block;
    text-align: center;
    vertical-align: middle;
    white-space: nowrap;
    padding: 0;
    border-width: 1px;
    border-radius: 4px;
    /* side color */ background-color: purple;
    /* outer border */ border-color: black;
    padding-bottom: 2px;
  }
  button > span {
    display: block;
    border-radius: 4px;
    margin: 0;
    padding: 0.3rem;
    color: white;
    /* surface border */ border: 1px solid pink;
    /* surface color */ background-color: purple;
  }
  button:hover {
    /* hover outer border color */ border-color: palevioletred;
  }
  button:hover > span {
    /* hover surface color */ background-color: darkmagenta;
  }
  button:not(:disabled):not(.disabled):active {
    /* active outer border */ border-color: palevioletred;
    padding-bottom: 0px;
    margin-top: 2px !important;
    outline: none;
    box-shadow: none;
    /* active side color */ background-color: purple;
  }
  button:not(:disabled):not(.disabled):active > span {
    /* active surface color */ background-color: darkmagenta;
  }
</style>

<button 
  role="button"
  on:click 
  on:mouseenter 
  on:mouseleave
  on:focus
  on:blur
>
  <span>
    <slot></slot>
  </span>
</button>

// react/src/components/Button/index.js
import React from "react"
import PropTypes from "prop-types"
import styled from "styled-components"
import { lighten, darken, transparentize } from "polished"

const activeStyles = `
  box-shadow: none;
  outline: 0;
`
const Button = styled.button`
  display: inline-block;
  margin-top: 0 !important;
  padding: 0;
  min-width: ${({ small }) => (small ? "32px" : "45px")};
  border-width: 1px;
  border-radius: 4px;
  padding-bottom: ${({ small }) => (small ? "1px" : "2px")};
  border-style: solid;
  box-shadow: none;
  cursor: pointer;
  font-size: ${({ theme, small }) =>
    small ? theme.fonts.sizes[0] : theme.fonts.sizes[1]};
  font-family: "AnonymousPro";
  line-height: 1.5;
  text-align: center;
  text-decoration: none;
  user-select: none;
  vertical-align: middle;
  white-space: nowrap;
  background-color: ${({ theme, variant }) => theme[variant].fg};
  border-color: ${({ theme, variant }) => theme[variant].bg};
  transition: all 0.15s cubic-bezier(0.25, 1, 0.5, 1);

  &:hover {
    border-color: ${({ theme, variant }) => lighten(0.05, theme[variant].bg)};
  }
  &:not(:disabled):not(.disabled):active {
      margin-top: ${({ small }) => (small ? "1px" : "2px")} !important;
      padding-bottom: 0px;
      background-color: ${({ theme, variant }) => theme[variant].fg};
      border-color: ${({ theme, variant }) => theme[variant].bg};
    }
  &:active,
  &.active {
    ${activeStyles}
  }
  &:focus {
    box-shadow: inset 0 1px 0
        ${({ theme, variant }) => transparentize(0.85, theme[variant].bg)},
      0 1px 1px
        ${({ theme, variant }) => transparentize(0.75, theme[variant].bg)},
      0 0 0 0.2rem
        ${({ theme, variant }) => transparentize(0.65, theme[variant].bg)};
    outline: 0;
  }
  & > span {
    display: block;
    height: 100%;
    box-sizing: inherit;
    overflow: hidden;
    width: 100%;
    margin: 0;
    padding: ${({ small }) => (small ? "4px" : "8px")};
    background-color: ${({ theme, variant }) => theme[variant].bg};
    border: 1px solid ${({ theme, variant }) => theme[variant].fg};
    color: ${({ theme, variant }) => theme[variant].text};
  }
  &:hover:not(:disabled):not(.disabled) > span {
    background-color: ${({ theme, variant }) =>
      lighten(0.05, theme[variant].bg)};
  }
  &:not(:disabled):not(.disabled):active > span {
    background-color: ${({ theme, variant }) =>
      darken(0.05, theme[variant].bg)};
  }
`

export const CuteButton = (props) => {
  const { children, variant = "primary", ...rest } = props
  const defaultText = "Make it so"
  const myChildren = typeof children === "undefined" ? defaultText : children

  return (
    <Button
      variant={variant}
      disabled={variant === "disabled"}
      {...rest}
    >
      <span>{myChildren}</span>
    </Button>
  )
}

CuteButton.propTypes = {
  variant: PropTypes.string,
  children: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.node),
    PropTypes.node,
  ]),
}
export default CuteButton
